### ISSUE TITLE
可以deploy到Github Pages吗

### ISSUE THREAD

**Issue by raygorous** [tangly1024/NotionNext#1401]
**为什么提出这个新的特性改动**
如果想选择github page作为个人首页和域名，免费且和github紧密连接

**描述一下你推荐的解决方案**
个人就不需要单独购买域名，直接用github的免费域名就可以了，直接通过github actions来解决自动部署的问题。

**描述一下你考虑过的其它替代解决方案**
不知道

**补充说明**
不知道notion update后需不需要手动deploy，才能显示来内容的更新。目前notionnext + Vercel不需要手动deploy，如果只是博客内容的更新的话。

**Comment by tangly1024** [comment]
github page 似乎只支持部署纯静态项目

**Comment by fdawnxl** [comment]
理论上可以，因为部署到Github Pages和Cloudflare Pages是一样的。而且现在的文档上写部署在CFP上需要手动部署，不过根据我自己以前的使用情况来看，只要部署的得当（能够产生可以被捕捉到的改动）就可以自动部署。

**Comment by aistart** [comment]
楼主当前在pages上部署成功了吗？

**Comment by Aj002Th** [comment]
我也很希望能 notion next 够提供这个部署方式。理论上 [部署] 应该可以通过配置 github actions 来实现导出纯静态内容，并将内容 push 到 github page 对应的仓库中来实现。关于博客内容在 notion 上修改后，更新如何 [同步更新内容] 的问题，也许可以通过 github actions 中的 cron 配置项设置 cron 表达式，来实现定时触发 actions 来实现。
```yaml
on:
    push:
    workflow_dispatch:
    schedule:
        # Runs everyday at 8:00 AM
        - cron: "0 0 * * *"
```
以后是否会考虑实现这个部署方式呢
