### ISSUE TITLE
环境变量配置NEXT_PUBLIC_THEME无效

### ISSUE THREAD

**Issue by zhang1zh** [tangly1024/NotionNext#2600]
**描述遇到的问题**
通过docker部署notionnext设置主题环境变量NEXT_PUBLIC_THEME无作用

**相应配置**
docker-compose配置如下：
```yml
services:
  notionnext:
    container_name: notionnext
    image: ghcr.io/tangly1024/notionnext:main
    ports:
      - 3333:3000
    environment: 
      NOTION_PAGE_ID: 24185cda07434fec80f93aab677d8455
      NEXT_PUBLIC_THEME: heo
    networks:
      - default
      - default_bridge
    labels:
      - traefik.http.routers.notionnext-main.rule=Host(`test.poohpooh.cn`)
    restart: always
networks:
  default_bridge:
    external: true
```
**截图**
正常应该根据环境变量中`NEXT_PUBLIC_THEME`为heo的配置，应用heo主题，但是无效果，在notion-config中配置`THEME`可以
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/380d68fd-e2ca-4000-9e04-240c29bc2036">

**环境**

```shell
root@Tower:~# docker images|grep notion
ghcr.io/tangly1024/notionnext                main           845fc23eeec1   6 days ago     931MB
root@Tower:~# docker exec -it notionnext /bin/sh
/app # env
NEXT_PUBLIC_THEME=heo
NODE_VERSION=18.20.3
HOSTNAME=8a382cc135c4
YARN_VERSION=1.22.19
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
NOTION_PAGE_ID=24185cda07434fec80f93aab677d8455
NODE_ENV=production
```
