### ISSUE TITLE
【两个建议】滚动条宽度，捐赠打赏功能

### ISSUE THREAD

**Issue by tangly1024** [tangly1024/NotionNext#728]
来自评论区 [飄颻](http://www.xauthub.top/) 的建议

1.页面右边拖动条的宽度可以调整吗
2.我看项目public下面有微信和支付宝的收款码，这两个怎么调用呢，可以给项目增加每个网页下面都有捐赠的功能吗

**Comment by tangly1024** [comment]
- 调整滚动条可以通过样式简单实现。
```css
body::-webkit-scrollbar {
    width: 10px;
}
```

- 打赏功能可以作为一个新特性后续版本实现。
